apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      port: 5000
      targetPort: {{ .Values.backend.port }}