apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-mysql-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ .Values.secrets.secretName }}
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.secretName }}
        property: password
