apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}