namespace: prod

backend:
  name: backend
  image: adarshjain428/backend:v12
  replicas: 2
  port: 5000

frontend:
  name: frontend
  image: adarshjain428/frontend:v13
  replicas: 2
  port: 80

database:
  host: crud-app.c47akookwd22.us-east-1.rds.amazonaws.com
  name: crud_app
  port: "3306"

secrets:
  awsRegion: us-east-1
  secretName: rds!db-9ffd2c44-ee29-4b66-aadb-eae4e36fc654
