namespace: prod

backend:
  name: backend
  image: adarshjain428/backend:v12
  replicas: 2
  port: 5000

frontend:
  name: frontend
  image: adarshjain428/frontend:v13
  replicas: 2
  port: 80

database:
  host: mysqldb.c47akookwd22.us-east-1.rds.amazonaws.com
  name: mysqldb
  port: "3306"

secrets:
  awsRegion: us-east-1
  secretName: rds!db-3422be04-40a4-4df1-bcba-f9cf315ce77d
